#Pos
#heatmap
```{r}
suppressPackageStartupMessages(library(pheatmap)) 

setwd("/rdsgpfs/general/user/mw519/home/dissertation/dissertation/mtb")
pdf("heatmap_mtb_pos_new.pdf",width=20,height=20) 

mycor = cor(denoised_pos1)

pheatmap(mycor, show_rownames = FALSE, show_colnames = FALSE, breaks = seq(-1, 1, length.out = 100))

dev.off()
```


#distribution
```{r}
setwd("/rdsgpfs/general/user/mw519/home/dissertation/dissertation/mtb")

pdf("Distributions_pos.pdf") 

par(mfrow = c(6, 6), mar = c(1, 1, 1, 1)) 
for (k in 1:ncol(denoised_pos1)) {
  xfull = density(denoised_pos1[, k])
  x0 = density(denoised_pos1[as.character(cov1$case) =="0", k])
  x1 = density(denoised_pos1[as.character(cov1$case) =="1", k])
  plot(density(denoised_pos1[, k]), col = "skyblue", xlab = "",
        main = "", ylab = colnames(denoised_pos1)[k], las = 1,
        ylim = range(c(xfull$y, x0$y, x1$y)))
  lines(x0, col = "darkgreen")
  lines(x1, col = "tomato")
  if (k == 1) {
    legend("topleft", lwd = 2, 
           col = c("skyblue", "darkgreen", "tomato"), 
           legend = c("Full sample", "Controls", "Cases"), cex = 0.7)
  }
}

dev.off()
```
```{r}
class(denoised_pos1[1,1])
```


```{r}
library(ggfortify)
pca_res_pos <- prcomp(denoised_pos1[1,1], scale. = TRUE)

names(denoised_pos1)[ncol(denoised_pos1)]<-"case"
denoised_pos1$case <- as.character(denoised_pos1$case)

#get pca plot
setwd("/rdsgpfs/general/user/mw519/home/dissertation/dissertation/mtb")

pdf("pca_denoised_pos.pdf")
autoplot(pca_res_pos, data = denoised_pos1)

#autoplot(pca_res_pos, data = denoised_pos1, colour = "case",scale = 0)

dev.off()
```
```{r}
sub_de_pos <- denoised_pos1[1:3,1:3]

pca_res_pos <- prcomp(sub_de_pos, scale. = TRUE)
```

```{r}
sum(is.na(denoised_pos1))
```


#Neg
#heatmap
```{r}
suppressPackageStartupMessages(library(pheatmap)) 

setwd("/rdsgpfs/general/user/mw519/home/dissertation/dissertation/mtb")
pdf("heatmap_mtb_neg_new.pdf",width=20,height=20) 

mycor = cor(denoised_neg1)

pheatmap(mycor, show_rownames = FALSE, show_colnames = FALSE, breaks = seq(-1, 1, length.out = 100))

dev.off()
```


#distribution
```{r}
setwd("/rdsgpfs/general/user/mw519/home/dissertation/dissertation/mtb")

pdf("Distributions_neg.pdf") 

par(mfrow = c(6, 6), mar = c(1, 1, 1, 1)) 
for (k in 1:ncol(denoised_neg1)) {
  xfull = density(denoised_neg1[, k])
  x0 = density(denoised_neg1[as.character(cov1$case) =="0", k])
  x1 = density(denoised_neg1[as.character(cov1$case) =="1", k])
  plot(density(denoised_neg1[, k]), col = "skyblue", xlab = "",
        main = "", ylab = colnames(denoised_neg1)[k], las = 1,
        ylim = range(c(xfull$y, x0$y, x1$y)))
  lines(x0, col = "darkgreen")
  lines(x1, col = "tomato")
  if (k == 1) {
    legend("topleft", lwd = 2, 
           col = c("skyblue", "darkgreen", "tomato"), 
           legend = c("Full sample", "Controls", "Cases"), cex = 0.7)
  }
}

dev.off()
```


```{r}
library(ggfortify)
pca_res <- prcomp(denoised_neg1, scale. = TRUE)

names(denoised_neg1)[ncol(denoised_neg1)]<-"case"
denoised_neg1$case <- as.character(denoised_neg1$case)

#get pca plot
setwd("/rdsgpfs/general/user/mw519/home/dissertation/dissertation/mtb")

pdf("neg_denoised_pos.pdf")
autoplot(pca_res, data = denoised_neg1, colour = "case",scale = 0)

dev.off()
```


